version: '3'
services:
  dnsserver:
    image: "stuvie/bind9"
    container_name: dnsserver
    environment:
      PASS: "cool"
    volumes:
      - ./data:/data
    ports:
      - "5553:53"
      # - "10000:10000"
      - "5553:53/udp"
